server:
  port: ${SERVER_PORT}

spring:
  application:
    name: vclipper-processing-orchestration
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${DB_HOST}:${DB_PORT}/${MONGODB_DATABASE}
      database: ${MONGODB_DATABASE}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  # Spring Cloud AWS Configuration
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      # Use default credentials provider (reads from ~/.aws/credentials) for development
      # In production, uncomment the explicit credentials below:
      credentials:
        instance-profile: false
        profile-name: default
        # Production configuration (commented out for development):
        # access-key: ${AWS_ACCESS_KEY_ID}
        # secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        enabled: true

# AWS Configuration
aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET}
  sqs:
    processing-queue-url: ${AWS_SQS_PROCESSING_QUEUE_URL}
    result-queue-url: ${AWS_SQS_RESULT_QUEUE_URL}
  sns:
    notification-topic-arn: ${AWS_SNS_NOTIFICATION_TOPIC_ARN}

vclipper:
  processing:
    video:
      max-size-bytes: ${VCLIPPER_MAX_FILE_SIZE_BYTES}
      allowed-formats: ${VCLIPPER_ALLOWED_FORMATS}
    download:
      url-expiration-minutes: ${VCLIPPER_DOWNLOAD_EXPIRATION_MINUTES}
    retry:
      max-attempts: ${VCLIPPER_RETRY_MAX_ATTEMPTS}
      initial-delay-seconds: ${VCLIPPER_RETRY_INITIAL_DELAY}
      max-delay-seconds: ${VCLIPPER_RETRY_MAX_DELAY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: VClipper Processing Orchestration Service
    description: Handles video upload, processing workflow orchestration, and status tracking
  features:
    - Video Upload & Validation
    - Processing Status Tracking
    - AWS S3 Integration (Mock)
    - SQS Message Publishing (Mock)
    - SNS Notifications (Mock)

logging:
  level:
    com.vclipper.processing: ${LOG_LEVEL_VCLIPPER}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB}
    org.springframework.data.mongodb: ${LOG_LEVEL_MONGODB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
